apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: home-security-secret-store
  namespace: home-security
spec:
  provider:
    kubernetes:
      remoteNamespace: home-security
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: default

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dashboard-credentials
  namespace: home-security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: home-security-secret-store
    kind: SecretStore
  target:
    name: dashboard-credentials
    creationPolicy: Owner
  data:
    - secretKey: ha-token
      remoteRef:
        key: dashboard-credentials
        property: ha-token
    - secretKey: ha-url
      remoteRef:
        key: dashboard-credentials
        property: ha-url
    - secretKey: database-url
      remoteRef:
        key: dashboard-credentials
        property: database-url
    - secretKey: dashboard-api-key
      remoteRef:
        key: dashboard-credentials
        property: dashboard-api-key
    - secretKey: dashboard-allowed-origins
      remoteRef:
        key: dashboard-credentials
        property: dashboard-allowed-origins

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-cameras
  namespace: home-security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: home-security-secret-store
    kind: SecretStore
  target:
    name: frigate-cameras
    creationPolicy: Owner
  data:
    - secretKey: FRIGATE_CAM_ENTRADA_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_ENTRADA_URL
    - secretKey: FRIGATE_CAM_ENTRADA_SUB_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_ENTRADA_SUB_URL
    - secretKey: FRIGATE_CAM_FUNDOS_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_FUNDOS_URL
    - secretKey: FRIGATE_CAM_FUNDOS_SUB_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_FUNDOS_SUB_URL
    - secretKey: FRIGATE_CAM_LATERAL_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_LATERAL_URL
    - secretKey: FRIGATE_CAM_LATERAL_SUB_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_LATERAL_SUB_URL
    - secretKey: FRIGATE_CAM_GARAGEM_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_GARAGEM_URL
    - secretKey: FRIGATE_CAM_GARAGEM_SUB_URL
      remoteRef:
        key: frigate-cameras
        property: FRIGATE_CAM_GARAGEM_SUB_URL
